seeder:
  file: ./seeder/seeder.rb
  disabled : false

parsers:
  - page_type: listings
    file: ./parsers/listings.rb
    disabled: false

  - page_type: products
    file: ./parsers/products.rb
    disabled: false

exporters:
  - exporter_name: products_json # Must be unique
    exporter_type: json
    collection: products
    write_mode: pretty_array # can be `line`,`pretty`, `pretty_array`, or `array`
    offset: 0 # offset to where the exported record will start from
    order: desc # can be ascending `asc` or descending `desc`
    start_on_job_done: true

  - exporter_name: products_csv
    exporter_type: csv
    collection: products
    start_on_job_done: true
    fields:
      - header: "gid"
        path: "_gid"
      - header: "created_at"
        path: "_created_at"
      - header: "listing_page"
        path: "listing_page"
      - header: "item_rank"
        path: "item_rank"
      - header: "title"
        path: "title"
      - header: "current_price"
        path: "current_price"
      - header: "original_price"
        path: "original_price"
      - header: "rating"
        path: "rating"
      - header: "publisher"
        path: "publisher"
      - header: "walmart_number"
        path: "walmart_number"
      - header: "img_url"
        path: "img_url"
      - header: "categories"
        path: "categories"